spring:
  application:
    name: helloworld
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ""
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 8080
  error:
    include-message: always

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# self config
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI4GKzjKQfjK8XjJjyVQvh
    accessKeySecret: jzK06Rl1KzjKQfjK8XjJjyVQvh
    bucketName: test-bucket-name
